### ISSUE TITLE
key code

### ISSUE THREAD

**Issue by czy341181** [lzrobots/dgmn#3]
Thanks for your great work.
your code is a project but it is too much.
I want to ask where is the key code of DGMN module?  Like figure 2 and figure 3 in your paper.

**Comment by lzrobots** [comment]
thanks for your interests. will find time to clean it.
The key code of dgmn is [here](https://github.com/lzrobots/dgmn/blob/master/maskrcnn_benchmark/layers/dynamic_weight.py
)
